(async function studio(){
'use strict';
const $=s=>document.querySelector(s),e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const status=s=>{$('#studio-status').textContent=s;};
let config,index;try{[config,index]=await Promise.all([fetch('/community-config.json').then(r=>r.json()),fetch('/api/rankings').then(r=>{if(!r.ok)throw Error('Chart unavailable');return r.json();})]);}catch{document.querySelector('#studio').textContent='The index could not load. Please refresh to retry.';return;}
const artists=index.artists,bySlug=s=>artists.find(a=>a.slug===s),root=$('#studio'),url=new URL(location.href),parts=url.pathname.split('/').filter(Boolean),view=parts[1]||'home';
let session;try{session=JSON.parse(sessionStorage.getItem('afri-account')||'null');}catch{}
async function api(path,options={}){
 if(session?.expires_at&&session.expires_at<Date.now()/1000){session=null;sessionStorage.removeItem('afri-account');}
 const headers={apikey:config.key,'Content-Type':'application/json',...(session?.access_token?{Authorization:`Bearer ${session.access_token}`}:{})};
 const response=await fetch(config.url+path,{...options,headers:{...headers,...options.headers}});const text=await response.text();let data;try{data=text?JSON.parse(text):null;}catch{data={message:'Service unavailable'};}
 if(!response.ok)throw Error(data.msg||data.message||data.error_description||'Request failed');return data;
}
const db=(path,options)=>api('/rest/v1/'+path,options);
async function requireUser(){if(!session?.access_token)throw Error('Sign in from My board first.');const user=await api('/auth/v1/user');return user;}
const safeAction=fn=>async event=>{try{await fn(event);}catch(err){status(err.message);}};
function bind(id,fn){const node=document.getElementById(id);if(node)node.addEventListener('click',safeAction(fn));}
function intro(title,text){root.innerHTML=`<p class="kicker">AFR / INDEX · The official chart stays locked</p><h1>${e(title)}</h1><p class="lede">${e(text)}</p>`;}
function rows(list){return list.map(a=>`<div class="row"><span class="rank">${a.rank??'—'}</span><a href="/current/${e(a.slug)}"><strong>${e(a.name)}</strong><br><small>${e(a.country)} · ${e((a.genres||[]).join(' / '))}</small></a><span>${a.score??'—'}</span><a aria-label="Share ${e(a.name)} ranking card" href="/api/card?artist=${e(a.slug)}&format=story">↗</a></div>`).join('');}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function receiptId(value){let id=value.trim();if(id.startsWith('http')){const u=new URL(id);if(u.origin!==location.origin)throw Error('Use an Afri Index receipt link.');id=u.pathname.split('/').at(-1);}if(!/^[a-f0-9-]{36}$/i.test(id))throw Error('Enter a valid receipt ID or link.');return id;}
async function readReceipt(value){const id=receiptId(value);const found=await db(`receipts?id=eq.${id}&select=id,payload,image,created_at`);if(!found.length)throw Error('Receipt is private, deleted, or unavailable.');return found[0];}
const normalize=s=>String(s||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
function overlap(a,b){const shared=[...a].filter(v=>b.has(v));return {shared,percent:Math.round(100*shared.length/(new Set([...a,...b]).size||1))};}
function chartWeek(date){const d=new Date(date);d.setUTCHours(0,0,0,0);d.setUTCDate(d.getUTCDate()+4-(d.getUTCDay()||7));const y=d.getUTCFullYear(),n=Math.ceil((((d-new Date(Date.UTC(y,0,1)))/86400000)+1)/7);return `${y}-W${String(n).padStart(2,'0')}`;}
async function home(){
 intro('The culture, in motion.','Explore the published chart, share an artist’s position, or build your own board. Movement compares available rank snapshots.');
 const ranked=artists.filter(a=>Number.isFinite(a.previousRank)),up=[...ranked].sort((a,b)=>(b.previousRank-b.rank)-(a.previousRank-a.rank)).filter(a=>a.previousRank>a.rank).slice(0,5),down=[...ranked].sort((a,b)=>(a.previousRank-a.rank)-(b.previousRank-b.rank)).filter(a=>a.previousRank<a.rank).slice(0,5);
 root.innerHTML+=`<p>Chart data as of ${e(index.asOf||'date unavailable')}</p><div class="grid"><section class="panel"><h2>Biggest risers</h2>${rows(up)}</section><section class="panel"><h2>Biggest drops</h2>${rows(down)}</section></div><section class="panel"><h2>One to watch</h2>${up[0]?rows([up[0]]):'<p>No verified movement yet.</p>'}</section><section class="panel"><h2>Debut watch · 51–75</h2>${rows(artists.filter(a=>a.rank>50&&a.rank<=75))||'<p class="empty">The published database currently covers the Current 50. Positions 51–75 and entry forecasts have not been verified.</p>'}</section><div class="actions"><a href="/week/${chartWeek(index.asOf)}">Read this edition</a><a href="/studio/graph">Explore collaborations</a><a href="/studio/catalogue">One-hit vs catalogue</a><a href="/studio/bracket">Weekly head-to-head</a><a href="/vs/${artists[0].slug}/${artists[1].slug}">Compare artists</a></div>`;
}
async function board(){
 intro('My board','Sign in to save up to ten artists, publish receipts, and keep track of changes.');
 root.innerHTML+=`<section class="panel"><h2>Sign in by email</h2><label>Email<input id="email" type="email" autocomplete="email"></label><button id="send-link">Send magic link</button><button id="sign-out">Sign out</button><p class="muted">Email delivery must be enabled for your account. Sessions stay in this tab.</p></section><section class="panel"><label>Username<input id="username" pattern="[a-z0-9_]{3,30}" maxlength="30"></label><label><input id="board-public" type="checkbox"> Make my profile and board public</label><div id="watch-picks"></div><button id="save-board">Save board</button></section><section class="panel"><h2>Your digest</h2><div id="digest">Sign in to load your board.</div></section><section class="panel"><h2>Saved receipts</h2><div id="saved-receipts"></div></section>`;
 $('#watch-picks').innerHTML=artists.map(a=>`<label><input type="checkbox" value="${e(a.slug)}" name="watch"> ${e(a.name)}</label>`).join('');
 bind('send-link',async()=>{const email=$('#email').value.trim();if(!$('#email').checkValidity()||!email)throw Error('Enter your email address.');await api('/auth/v1/otp?redirect_to='+encodeURIComponent(location.origin+'/studio/board'),{method:'POST',body:JSON.stringify({email,create_user:true})});status('Check your email for a sign-in link.');});
 bind('sign-out',async()=>{if(session)await api('/auth/v1/logout',{method:'POST'});session=null;sessionStorage.removeItem('afri-account');location.reload();});
 bind('save-board',async()=>{const user=await requireUser(),username=$('#username').value.trim();if(!/^[a-z0-9_]{3,30}$/.test(username))throw Error('Use 3–30 lowercase letters, numbers, or underscores.');const picks=[...document.querySelectorAll('[name=watch]:checked')].map(n=>n.value);if(picks.length<5||picks.length>10)throw Error('Choose 5–10 artists.');await db('profiles?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates'},body:JSON.stringify({id:user.id,username,board_public:$('#board-public').checked,board:picks.map(slug=>({slug,rank:bySlug(slug).rank,checkedAt:index.asOf}))})});status('Board saved.');});
 if(session){const user=await requireUser(),profiles=await db(`profiles?id=eq.${user.id}`),p=profiles[0];if(p){$('#username').value=p.username;$('#board-public').checked=p.board_public;document.querySelectorAll('[name=watch]').forEach(n=>n.checked=p.board.some(a=>a.slug===n.value));$('#digest').innerHTML=p.board.map(old=>{const a=bySlug(old.slug);return `<p>${e(a?.name||old.slug)}: ${a?old.rank===a.rank?'no rank change':`#${old.rank} → #${a.rank}`:'outside the current published board'}</p>`;}).join('');}
 const receipts=await db(`receipts?user_id=eq.${user.id}&select=id,created_at,public&order=created_at.desc&limit=20`);$('#saved-receipts').innerHTML=receipts.map(r=>`<div class="row"><a href="/receipt/${r.id}">${e(r.created_at.slice(0,10))} · ${r.public?'Public':'Private'}</a><button data-delete="${r.id}">Delete</button></div>`).join('')||'<p>No saved receipts yet.</p>';document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=safeAction(async()=>{await db(`receipts?id=eq.${b.dataset.delete}`,{method:'DELETE'});b.closest('.row').remove();status('Receipt deleted.');}));}
}
async function comparison(group=false){
 intro(group?'House ranking':'Music twins?',group?'Combine 3–8 shared receipts. Each receipt contributes equal ranked points to your group’s top ten.':'Paste two public receipt links. Match scores use shared artists divided by the combined unique artist list.');
 root.innerHTML+=`<section class="panel"><label>${group?'One receipt link per line':'First receipt'}<textarea id="first" rows="${group?5:2}"></textarea></label>${group?'':'<label>Second receipt<textarea id="second" rows="2"></textarea></label>'}<button id="compare">${group?'Build house receipt':'Compare'}</button></section><div id="comparison"></div>`;
 bind('compare',async()=>{const values=group?$('#first').value.trim().split(/\n+/):[$('#first').value,$('#second').value];if(group&&(values.length<3||values.length>8))throw Error('Use 3–8 receipt links.');const ids=values.map(receiptId);if(new Set(ids).size!==ids.length)throw Error('Each receipt must be different.');const list=await Promise.all(values.map(readReceipt));
 if(group){const points=new Map();list.forEach(r=>{const seen=new Set();(r.payload.artists||[]).slice(0,10).forEach((a,i)=>{const key=normalize(a.name);if(seen.has(key))return;seen.add(key);const old=points.get(key)||{name:a.name,points:0};old.points+=10-i;points.set(key,old);});});const top=[...points.values()].sort((a,b)=>b.points-a.points).slice(0,10);$('#comparison').innerHTML='<canvas id="house" class="story-canvas" width="1080" height="1920"></canvas><button id="house-download">Download PNG</button>';const canvas=$('#house'),ctx=canvas.getContext('2d');ctx.fillStyle='#1c1c1a';ctx.fillRect(0,0,1080,1920);ctx.fillStyle='#d7f04a';ctx.font='bold 60px monospace';ctx.fillText('AFR / INDEX',80,140);ctx.font='40px monospace';ctx.fillText('HOUSE RANKING',80,230);ctx.font='26px monospace';ctx.fillText(`${list.length} receipts · Equal ranked points`,80,300);top.forEach((a,i)=>{ctx.fillStyle='#e8e6d8';ctx.font='36px monospace';ctx.fillText(`${i+1}. ${a.name}`.slice(0,35),80,420+i*110);ctx.fillStyle='#d7f04a';ctx.font='22px monospace';ctx.fillText(`${a.points} house points`,120,455+i*110);});ctx.font='24px monospace';ctx.fillText('COMMUNITY PICKS · OFFICIAL CHART UNCHANGED',80,1770);bind('house-download',()=>canvas.toBlob(blob=>downloadBlob(blob,'afri-house.png')));return;}
 const [a,b]=list,as=new Set((a.payload.artists||[]).map(x=>normalize(x.name))),bs=new Set((b.payload.artists||[]).map(x=>normalize(x.name))),result=overlap(as,bs);const tracks=r=>new Set((r.payload.tracks||[]).map(t=>normalize(t.title)+' — '+normalize(t.artist)));const sharedTracks=overlap(tracks(a),tracks(b));$('#comparison').innerHTML=`<section class="panel"><h2>${result.percent}% music twins</h2><p>Shared artists: ${e(result.shared.join(', ')||'None yet')}</p><p>Shared tracks: ${e(sharedTracks.shared.join(', ')||'None yet')}</p><p>${result.percent>=60?'Your playlists already know each other.':result.percent>=25?'Enough overlap for a shared aux cord.':'Two different lanes. Plenty to discover.'}</p></section><div class="grid">${list.map(r=>`<img class="receipt-image" src="/api/receipt-image?id=${r.id}" alt="Music receipt for comparison">`).join('')}</div>`;});
}
async function receipt(){const r=await readReceipt(parts[1]);intro('Music Receipt','Shared by its creator. Listening ranges and sources are recorded on the receipt.');root.innerHTML+=`<img class="receipt-image" src="${r.image.startsWith('data:image/png;base64,')?e(r.image):'/api/receipt-image?id='+r.id}" alt="Afri Index music receipt"><div class="actions"><a href="/api/receipt-image?id=${r.id}" download>Download PNG</a><a href="/studio/compare">Compare with a friend</a></div>`;}
async function profile(){const list=await db(`profiles?username=eq.${encodeURIComponent(parts[1])}&select=*`);if(!list.length)throw Error('Profile is private or unavailable.');const p=list[0];intro('@'+p.username,'A personal board. The official chart remains independent.');root.innerHTML+=rows(p.board.map(x=>bySlug(x.slug)).filter(Boolean));const rs=await db(`receipts?user_id=eq.${p.id}&public=eq.true&select=id&order=created_at.desc&limit=1`);if(rs[0])root.innerHTML+=`<h2>Latest receipt</h2><a href="/receipt/${rs[0].id}"><img class="receipt-image" src="/api/receipt-image?id=${rs[0].id}" alt="Latest public receipt"></a>`;}
async function artist(){const a=bySlug(parts[1]);if(!a)throw Error('Artist not found.');intro(a.name,a.bio||'Artist file');root.innerHTML+=`<p class="kicker">#${a.rank} Current · ${e(a.country)}</p><div class="actions"><button id="share-card">Share ranking card</button><a href="/api/card?artist=${a.slug}&format=story" download>Download Story PNG</a><a href="https://twitter.com/intent/tweet?text=${encodeURIComponent(`${a.name} is #${a.rank} on Afri Index ${location.href}`)}" target="_blank" rel="noopener">X</a><a href="https://wa.me/?text=${encodeURIComponent(`${a.name} is #${a.rank} on Afri Index ${location.href}`)}" target="_blank" rel="noopener">WhatsApp</a><a href="/studio/board">Watch artist</a></div><p>Monthly listeners: ${Number(a.monthlyListeners).toLocaleString()}${a.monthlyListenersApproximate?' (rounded source count)':''} · as of ${e(a.monthlyListenersLastUpdatedAt||a.statsLastUpdatedAt)}</p><p>Tracked catalogue: ${Number(a.totalSpotifyStreams).toLocaleString()} streams</p><section class="panel"><h2>Sources</h2>${Object.entries(a.sources||{}).filter(([,v])=>String(v).startsWith('https://')).map(([k,v])=>`<p><a href="${e(v)}" rel="noopener" target="_blank">${e(k)}</a></p>`).join('')}</section><section class="panel"><h2>Submit a correction</h2><label>What needs correcting?<textarea id="correction" maxlength="2000"></textarea></label><label>Source link<input id="source-url" type="url" placeholder="https://…"></label><button id="send-correction">Submit to editorial queue</button></section><section class="panel"><h2>Artist discussion</h2><div id="comments"></div><label>Your comment<textarea id="comment" maxlength="1000"></textarea></label><button id="post-comment">Submit for moderation</button></section>`;
 bind('share-card',async()=>{const blob=await fetch(`/api/card?artist=${a.slug}&format=story`).then(r=>r.blob()),file=new File([blob],'afri-ranking.png',{type:'image/png'});if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file],text:`${a.name} · #${a.rank} Current on Afri Index`});else downloadBlob(blob,'afri-ranking.png');});
 bind('send-correction',async()=>{const user=await requireUser(),source=$('#source-url').value.trim(),note=$('#correction').value.trim();if(!/^https:\/\//.test(source)||note.length<5)throw Error('Add a description and HTTPS source.');await db('corrections',{method:'POST',body:JSON.stringify({user_id:user.id,artist_slug:a.slug,note,source_url:source})});status('Correction submitted for editorial review.');});
 bind('post-comment',async()=>{const user=await requireUser(),body=$('#comment').value.trim();if(!body)throw Error('Write a comment first.');await db('comments',{method:'POST',body:JSON.stringify({user_id:user.id,artist_slug:a.slug,body})});status('Comment submitted. It will appear after moderation.');});
 const guide=index.recognition?.[a.slug];if(guide){const section=document.createElement('section');section.className='panel';section.innerHTML='<h2>Awards & certifications ledger</h2><p>From the existing editorial record. Individual entries retain their source context.</p>'+ (guide.records||[]).map(r=>`<p>${e(r.year)} · ${e(r.name)} · ${e(r.category)} · ${e(r.result)}</p>`).join('')+(guide.wikipedia_url?`<a href="${e(guide.wikipedia_url)}" target="_blank" rel="noopener">Source guide</a>`:'');root.append(section);}
 const cs=await db(`comments?artist_slug=eq.${a.slug}&approved=eq.true&order=created_at.desc&limit=50`);$('#comments').innerHTML=cs.map(c=>`<div class="panel"><p>${e(c.body)}</p><button data-report="${c.id}">Report</button></div>`).join('')||'<p>No approved comments yet.</p>';document.querySelectorAll('[data-report]').forEach(b=>b.onclick=safeAction(async()=>{const user=await requireUser();await db('comment_reports',{method:'POST',body:JSON.stringify({user_id:user.id,comment_id:b.dataset.report,reason:'Requested editorial review'})});status('Report submitted.');}));
}
async function sandbox(){intro('Show your weights','An experimental order never changes the official chart. A complete scenario needs the 11 published component scores for every artist.');const metrics=await db('artist_metrics?select=artist_slug,factors'),map=new Map(metrics.map(x=>[x.artist_slug,x.factors]));const complete=artists.every(a=>Array.isArray(map.get(a.slug))&&map.get(a.slug).length===11&&map.get(a.slug).every(Number.isFinite));root.innerHTML+=`<div class="grid"><section class="panel" id="sliders">${index.factorNames.map((name,i)=>`<label>${e(name)} <output id="w${i}">${index.weights[i]}</output><input data-factor="${i}" type="range" min="0" max="100" value="${index.weights[i]}"></label>`).join('')}<button id="reset-weights">Reset weights</button><p id="weight-total"></p></section><section class="panel"><h2>${complete?'Your scenario':'Published Current 50'}</h2>${complete?'':'<p class="empty">Component score evidence is not published yet. The sliders can be explored, but re-ranking is unavailable until those inputs are supplied.</p>'}<div id="sandbox-list">${rows(artists)}</div></section></div>`;
 function update(){const weights=[...document.querySelectorAll('[data-factor]')].map(n=>Number(n.value)),sum=weights.reduce((a,b)=>a+b,0);weights.forEach((w,i)=>$('#w'+i).textContent=w);$('#weight-total').textContent=sum?`Total ${sum}; normalized to 100% for calculation.`:'Choose at least one nonzero weight.';if(complete&&sum){const ranked=artists.map(a=>({...a,score:map.get(a.slug).reduce((n,v,i)=>n+v*weights[i],0)/sum})).sort((a,b)=>b.score-a.score).map((a,i)=>({...a,rank:i+1,score:a.score.toFixed(2)}));$('#sandbox-list').innerHTML=rows(ranked);}}
 document.querySelectorAll('[data-factor]').forEach(n=>n.oninput=update);bind('reset-weights',()=>{document.querySelectorAll('[data-factor]').forEach((n,i)=>n.value=index.weights[i]);update();});update();}
async function catalogue(){intro('One-hit vs catalogue','A streaming concentration proxy: the largest tracked song divided by tracked catalogue streams. This is not a decomposition of the official score; song and catalogue observations may have different dates.');root.innerHTML+=`<label>Order<select id="concentration"><option value="high">Most concentrated</option><option value="low">Most distributed</option><option value="official">Official rank</option></select></label><div id="concentration-list"></div>`;function render(){const list=artists.map(a=>({...a,share:a.totalSpotifyStreams?Math.max(0,...(a.songs||[]).map(s=>Number(s.streams)||0))/a.totalSpotifyStreams:null})).filter(a=>a.share!==null&&a.share<=1);list.sort((a,b)=>$('#concentration').value==='official'?a.rank-b.rank:$('#concentration').value==='low'?a.share-b.share:b.share-a.share);$('#concentration-list').innerHTML=list.map(a=>`<div class="row"><a href="/current/${a.slug}">${e(a.name)} · Official #${a.rank}</a><span>${(a.share*100).toFixed(1)}% of tracked streams</span></div>`).join('');}$('#concentration').onchange=render;render();}
async function boards(){intro('Different questions. Same evidence.','Specialist boards publish only when their criteria and source coverage can be verified.');const metrics=await db('artist_metrics?select=*'),map=new Map(metrics.map(x=>[x.artist_slug,x]));const defs=[['Women’s Current 25','A standalone view ordered by the published Current score.',a=>map.get(a.slug)?.gender==='woman'],['Veterans','Artists with at least 15 years of verified career history.',a=>Number.isInteger(map.get(a.slug)?.career_started)&&new Date().getFullYear()-map.get(a.slug).career_started>=15]];root.innerHTML+=defs.map(([title,desc,predicate])=>{const list=artists.filter(predicate).sort((a,b)=>b.score-a.score).slice(0,25);return `<section class="panel"><h2>${title}</h2><p>${desc}</p>${list.length?rows(list):'<p class="empty">Eligibility sources are awaiting editorial verification.</p>'}</section>`;}).join('');root.innerHTML+=['Featured-on index — verified guest credits and impact inputs','Producer & songwriter 25 — complete record credits and chart impact','Local vs international — country-level listening data'].map(x=>`<section class="panel"><h2>${e(x.split(' — ')[0])}</h2><p class="empty">Requires ${e(x.split(' — ')[1])}. The current database does not supply this evidence.</p></section>`).join('');}
async function graph(){intro('Who connects the culture?','Select an artist to expand collaborations explicitly named in the tracked song titles. Producer links require verified credits.');root.innerHTML+=`<label>Artist<select id="graph-artist">${artists.map(a=>`<option value="${a.slug}">${e(a.name)}</option>`).join('')}</select></label><div id="graph-output"></div>`;function render(){const a=bySlug($('#graph-artist').value),links=[];artists.forEach(b=>{if(a.slug===b.slug)return;const records=[...(a.songs||[]).filter(s=>normalize(s.title).includes(normalize(b.name))),...(b.songs||[]).filter(s=>normalize(s.title).includes(normalize(a.name)))];if(records.length)links.push({b,records});});$('#graph-output').innerHTML=`<section class="panel"><h2>${e(a.name)}</h2><div class="graph">${links.map(({b,records})=>`<a href="/current/${b.slug}"><strong>${e(b.name)}</strong><br><small>${e(records.map(s=>s.title).join(' · '))}</small></a>`).join('')||'<p>No explicitly credited collaboration matches in this snapshot.</p>'}</div></section>`;}$('#graph-artist').onchange=render;render();}
async function calendar(){intro('The culture calendar','Verified certifications, awards and live dates. Each event keeps its source and verification date.');const events=await db('editorial_events?order=event_date.asc&limit=100');root.innerHTML+=events.length?events.map(x=>`<section class="panel"><p class="kicker">${e(x.kind)} · ${e(x.event_date||'Date not supplied')}</p><h2>${e(x.title)}</h2><p>${e(bySlug(x.artist_slug)?.name||x.artist_slug)}</p><a href="${e(x.source_url)}" target="_blank" rel="noopener">Source · verified ${e(x.verified_at)}</a></section>`).join(''):'<p class="empty">No calendar events have been verified in the new database yet. Artist source links remain available on each profile.</p>';}
async function versus(){const picks=parts.slice(1,4).map(bySlug).filter(Boolean);intro('Head to head','Compare two or three artists from the same locked snapshot.');root.innerHTML+=`<label>Add a third artist<select id="third"><option value="">Choose an artist</option>${artists.filter(a=>!picks.includes(a)).map(a=>`<option value="${a.slug}">${e(a.name)}</option>`).join('')}</select></label><div class="grid">${picks.map(a=>`<section class="panel"><h2><a href="/current/${a.slug}">${e(a.name)}</a></h2><p>#${a.rank} Current · Score ${a.score}</p><p>${Number(a.monthlyListeners).toLocaleString()} monthly listeners</p><p>${Number(a.totalSpotifyStreams).toLocaleString()} tracked streams</p></section>`).join('')}</div>`;$('#third').onchange=()=>{if($('#third').value)location.href='/vs/'+picks.slice(0,2).map(a=>a.slug).concat($('#third').value).join('/');};}
async function edition(){let data=index;const week=parts[0]==='week'?parts[1]:chartWeek(index.asOf);if(parts[0]==='week'){const r=await fetch('/api/rankings?week='+encodeURIComponent(week));if(!r.ok)throw Error('This weekly edition has not been published.');data=await r.json();}intro('Week '+week,'The locked weekly edition. Print or save as PDF from your browser’s print dialog.');root.innerHTML+=`<div class="actions"><button id="print-edition">Print / save PDF</button><button id="paper">Broadsheet view</button><a href="/api/rankings?format=csv&week=${week}">CSV</a></div>${rows(data.artists)}`;bind('print-edition',()=>window.print());bind('paper',()=>document.body.classList.toggle('paper'));}
async function bracket(){intro('Weekly head-to-head','Community votes never affect the official chart. One vote per signed-in account. Results publish after voting closes.');const list=await db('brackets?order=closes_at.desc&limit=1');if(!list.length){root.innerHTML+='<p class="empty">The next bracket has not been published.</p>';return;}const b=list[0];root.innerHTML+=`<section class="panel"><h2>${e(bySlug(b.artist_a)?.name)} vs ${e(bySlug(b.artist_b)?.name)}</h2><p>Closes ${e(b.closes_at)}</p>${[b.artist_a,b.artist_b].map(s=>`<button data-vote="${e(s)}" ${new Date(b.closes_at)<new Date()?'disabled':''}>${e(bySlug(s)?.name)}</button>`).join('')}</section>`;if(new Date(b.closes_at)<new Date()){const results=await db(`bracket_results?week=eq.${b.week}`);root.innerHTML+=results.length?results.map(r=>`<p>${e(bySlug(r.choice)?.name)}: ${r.votes} votes</p>`).join(''):'<p>Results publish after the Sunday tally.</p>';}document.querySelectorAll('[data-vote]').forEach(n=>n.onclick=safeAction(async()=>{const user=await requireUser();await db('votes',{method:'POST',body:JSON.stringify({user_id:user.id,week:b.week,choice:n.dataset.vote})});status('Vote recorded. Your official chart is unchanged.');document.querySelectorAll('[data-vote]').forEach(b=>b.disabled=true);}));}
async function toolsPage(){intro('Take the index with you','Cite the snapshot date when using exported data.');root.innerHTML+=`<section class="panel"><h2>Public data</h2><div class="actions"><a href="/api/rankings">Current JSON API</a><a href="/api/rankings?format=csv">Download CSV</a><a href="/week/${chartWeek(index.asOf)}">Printable edition</a></div><p>Weekly editions: <code>/api/rankings?week=YYYY-Www</code>. Unpublished weeks return 404.</p></section><section class="panel"><h2>Embed the Current 10</h2><pre>${e('<iframe src="'+location.origin+'/api/widget" title="Afri Index Current Top 10" width="100%" height="740" loading="lazy"></iframe>')}</pre><iframe src="/api/widget" title="Current Top 10 preview" width="100%" height="740"></iframe></section><section class="panel"><h2>Offline reading</h2><p>The last downloaded official chart is available offline. Account data and private receipts are never cached.</p><button id="offline">Save chart for offline</button></section><section class="panel"><h2>Weekly notifications</h2><p class="empty">Push delivery needs a configured notification sender. No subscription is collected until that service is ready.</p></section>`;bind('offline',async()=>{if(!('serviceWorker'in navigator))throw Error('Offline support is unavailable in this browser.');await navigator.serviceWorker.register('/sw.js');status('Offline chart reader installed. Open Offline edition once while online.');});root.innerHTML+='<a href="/offline.html">Offline edition</a>';}
const hash=new URLSearchParams(location.hash.slice(1));if(hash.has('access_token')){session={access_token:hash.get('access_token'),expires_at:Math.floor(Date.now()/1000)+Number(hash.get('expires_in')||3600)};sessionStorage.setItem('afri-account',JSON.stringify(session));history.replaceState({},'',location.pathname);try{await requireUser();}catch{session=null;sessionStorage.removeItem('afri-account');}}
$('#command-open').onclick=()=>{$('#command-dialog').showModal();$('#command-input').focus();};document.addEventListener('keydown',event=>{if(event.key==='/'&&!/INPUT|TEXTAREA|SELECT/.test(event.target.tagName)&&!event.target.isContentEditable){event.preventDefault();$('#command-dialog').showModal();$('#command-input').focus();}});$('#command-input').oninput=()=>{const q=normalize($('#command-input').value);$('#command-results').innerHTML=artists.filter(a=>normalize(a.name).includes(q)).slice(0,10).map(a=>`<a href="/current/${a.slug}">${e(a.name)}</a>`).join('')+['board','compare','group','sandbox','calendar','tools'].filter(s=>s.includes(q)).map(s=>`<a href="/studio/${s}">${s}</a>`).join('');};
try{if(parts[0]==='receipt')await receipt();else if(parts[0]==='current')await artist();else if(parts[0]==='u')await profile();else if(parts[0]==='vs')await versus();else if(parts[0]==='week')await edition();else await ({home,board,compare:()=>comparison(),group:()=>comparison(true),sandbox,catalogue,boards,graph,calendar,tools:toolsPage,bracket}[view]||home)();}catch(err){status(err.message);root.innerHTML='<h1>Unable to load this view</h1><p>Please retry or return to <a href="/studio">the studio</a>.</p>';}
})();
